server:
  port: 2021
spring:
  application:
    name: field-compare
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      master:
        url: jdbc:mysql://localhost:3306/compare?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: xiajun
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        enable: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false